mypkg/objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>Associated_Interviewer__c</fullName>
        <label>Associated Interviewer</label>
        <referenceTo>Interviewer__c</referenceTo>
        <relationshipLabel>Candidates</relationshipLabel>
        <relationshipName>Candidates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Full_Name__c</fullName>
        <label>Full Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Position_Offered__c</fullName>
        <label>Position Offered</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GENC</fullName>
                </value>
                <value>
                    <fullName>GENCNEXT</fullName>
                </value>
                <value>
                    <fullName>GENCELEVATE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>CN-{000}</displayFormat>
        <label>Candidate No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mypkg/objects/Interviewer__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Age__c</fullName>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Full_Name__c</fullName>
        <label>Full Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pin_Code__c</fullName>
        <label>Pin Code</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Interviewer</label>
    <nameField>
        <displayFormat>IN-{000}</displayFormat>
        <label>Interviewer No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviewers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/TriggerInterviewTest.cls
@isTest
public class TriggerInterviewTest {
  static testMethod void interCandidate()
  {
      Test.startTest();
      Interviewer__c interviewer = new Interviewer__c();
      interviewer.Full_Name__c = 'Vismay Lall';
      interviewer.Age__c = 23;
      interviewer.Address__c = 'ABC Street';
      interviewer.Pin_Code__c = 1234;
      insert interviewer;
      
      Candidate__c candidate = new candidate__c();
      candidate.Associated_Interviewer__c = interviewer.Id;
      candidate.Full_Name__c = 'Sneha Singh';
      candidate.Position_Offered__c = 'GENC';
      insert candidate;
      
      try{
          delete interviewer;
      }
      catch(DMLException e){
          System.assert(e.getMessage().contains('Interviewer cannot be deleted'), 'Interviewer cannot be deleted');
      }
      Test.stopTest();
  }
}