mypkg/objects/Cart__c.object
<CustomObject>
    <fields>
        <fullName>Order_Placed__c</fullName>
        <label>Order Placed</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Send_Order_Confirmation_Mail__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Order Confirmation Mail</label>
        <type>Checkbox</type>
    </fields>
    <label>Cart</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Cart Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/classes/UpdateOrder.cls
global class UpdateOrder implements Database.Batchable<sObject> {
global database.QueryLocator start(Database.BatchableContext bc)
{
    return Database.getQueryLocator([Select Send_Order_Confirmation_Mail__c, Order_Placed__c from Cart__c]);
}
    global void execute(Database.BatchableContext bc,list<Cart__c> lList)
    {
        for(Cart__c l : lList)
        {
            if(l.Send_Order_Confirmation_Mail__c)
            l.Order_Placed__c = 'Yes';
        }
        update lList;
    }

        global void finish(Database.BatchableContext bc)
        {
            
        }
}