mypkg/objects/Cart__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Paid__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount Paid</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_Payable__c</fullName>
        <formula>IF( E_Voucher__c =&quot;WELCOME25&quot;, Total_Amount__c  -  Discount_After_EVoucher__c,  Total_Amount__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount Payable</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Confirm_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Confirm Order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Cart</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Cart Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/classes/CartController.cls
public class CartController {
    @AuraEnabled
    public static List <Cart__c> getAccounts() {
        return [SELECT Id, First_Name__c, Last_Name__c, Amount_Payable__c,Amount_Paid__c FROM Cart__c Where Confirm_Order__c=true ORDER BY createdDate ASC];
    }    
    @AuraEnabled
    public static List<Cart__c> findByName(String searchKey) {
        String name =  + searchKey + '%';
        return [SELECT id, First_Name__c, Last_Name__c, Amount_Payable__c,Amount_Paid__c FROM Cart__c WHERE Confirm_Order__c=true AND First_Name__c LIKE :name];
    }
}